###Cadastro do usuário

POST https://parkeasybd.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Clara",
    "email": "claram@gmail.com",
    "usuario": "clarawm",
    "password": "Clara1",
    "document": "020.654.376-00",
    "telefone": "35997663806",
    "sexo": "Feminino",
    "datanasc": "23/03/2005"

}

###Login do usuário

POST https://parkeasybd.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "document": "020.654.376-00",
    "password": "Clara1"
}

###Cadastro do estacionamento

POST https://parkeasybd.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "João da Silva",
    "email": "easyest@gmail.com",
    "usuario": "EasyEst",
    "password": "easy123",
    "document": "57.283.899/0001-14",
    "telefone": "3532246987",
    "cep": "37044-180",
    "razao":"Easy Estacionamento",
    "cidade":"Varginha",
    "bairro": "Cidade Nova",
    "numero": "7",
    "atendimento": "Segundo a Sábado"

}

###Login do estacionamento

POST https://parkeasybd.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "document": "57.283.899/0001-14",
    "password": "easy123"
}

###Cadastro de veículo

POST https://parkeasybd.onrender.com/veiculo HTTP/1.1
Content-Type: application/json
Authorization: bearer Mg.Ob4WZNgN7811ZjRTIVBnEAEIQIqd3qe42JGlgx3vM5QpztUl6x09aL28TgN5

{
    "placa": "MNX-6194",
    "cor": "Vermelho",
    "marca": "Chevrolet",
    "modelo": "Camaro" 

}

###Cadastrar Voucher

POST https://parkeasybd.onrender.com/cadastrarVoucher HTTP/1.1
Content-Type: application/json
Authorization: bearer Mg.Ob4WZNgN7811ZjRTIVBnEAEIQIqd3qe42JGlgx3vM5QpztUl6x09aL28TgN5

{
    "datad": "07/11/2023",
    "quantidade": "5",
    "horario_inicio": "08:30",
    "horario_termino": "10:00",
    "valor": "R$20,00"
}
