###Login do usuário

POST https://parkeasybd.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Clara",
    "email": "claram@gmail.com",
    "usuario": "clarawm",
    "password": "12345",
    "document": "123.456.789-12",
    "telefone": "35997663806",
    "sexo": "Feminino",
    "datanasc": "23/03/2005"

}

###Autenticação do usuário

POST https://parkeasybd.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "document": "123.456.789-12",
    "password": "12345"
}